# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job password: ${{ secrets.SERVER_PASSWORD }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access 
      - uses: actions/checkout@v2

      - name: scp file
        uses: appleboy/scp-action@master
        with:
          host:  ${{ secrets.HOST }}
          username: 'root'
          port: 22
          key: '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA+4FjxSRkyN7w3Wg2jEdvY314bDMy3ICvoBDOcYhZl991dFPIy41P
dNX1pwmNBt56ACUlbT3Fhc+O0wQ5Cdj7nCtD5C7b4r6IwCh6eLWQa0jnLNCucCQ9Th8MiY
7aqVo8hX3LChZYrx7zZCfagSaHPWdCrriDTTJwopM1zHZlNVYBAMwqGTTwCbZlkoNqlPks
yCUKoQxSRuxMzuztaxaMnh6XVNk4vF3UZpHQXeNi89Z2umO4yUVGhTiyZwdtf+YE3drSVS
lGSJU3QE3/JMGH9QNy8TQEVRWvL7sw1/C0JiHik0dmbnXMF00KPwcHV1Pr/ZCuPjrAxId3
UWx1Ng6SsEXM2V+UDPUO+cjSQ6iD8bdfTWmCl4e0cPg8WSE+Ycj8ilyGUmy//GZLXNCetS
IbW/oANx2pS4XNoRF4sPXsIdJVF/7wZsWnlcUVOQF10pM5QGhWcOUMqUsKAPad8s6a8fs/
Myy1cInAhyC33JvgkJhqQf387e2emFo88qcsSh95AAAFiDP4fJ4z+HyeAAAAB3NzaC1yc2
EAAAGBAPuBY8UkZMje8N1oNoxHb2N9eGwzMtyAr6AQznGIWZffdXRTyMuNT3TV9acJjQbe
egAlJW09xYXPjtMEOQnY+5wrQ+Qu2+K+iMAoeni1kGtI5yzQrnAkPU4fDImO2qlaPIV9yw
oWWK8e82Qn2oEmhz1nQq64g00ycKKTNcx2ZTVWAQDMKhk08Am2ZZKDapT5LMglCqEMUkbs
TM7s7WsWjJ4el1TZOLxd1GaR0F3jYvPWdrpjuMlFRoU4smcHbX/mBN3a0lUpRkiVN0BN/y
TBh/UDcvE0BFUVry+7MNfwtCYh4pNHZm51zBdNCj8HB1dT6/2Qrj46wMSHd1FsdTYOkrBF
zNlflAz1DvnI0kOog/G3X01pgpeHtHD4PFkhPmHI/IpchlJsv/xmS1zQnrUiG1v6ADcdqU
uFzaEReLD17CHSVRf+8GbFp5XFFTkBddKTOUBoVnDlDKlLCgD2nfLOmvH7PzMstXCJwIcg
t9yb4JCYakH9/O3tnphaPPKnLEofeQAAAAMBAAEAAAGBAJ5xgjAlYFTnlmh1ib/QFQ1hcy
b/DjC55Wp6jAQcOQ0jmrQhQGNz77WUQUDtFGpaaBOFU1HB05kcDEdF5sUcbE6TNx8eoinz
jOU52wYGpCficrjZ8rr1KaX4i4Zxd7GvBme2ut3s/Au+/OiA7vfkFNkLH4hA937/otPY19
CqWdJDDzi4ZmEg54PG47BsmA2n+J1SMKMKxx6lKTJHMr7/IrFOZlnuyv5oQjIn9FPht2oU
FxIPVs99lBLDiCi+Fi638eM4V8dMF3WU4JUpJqFyQFL4Pa8yna4qXHYCxkpNhsL1VKr9+u
1VvGOD8oMI/xbO7FaQ94/ec660hChOBFIM3LkAL16GSS9Wlo5r268UttqKIN2bo+IlN6Dq
y74KJXZ+cs7ICLRvejus1uUV7u8M1ldnADOpjLG+TOj6G2Ce/EDArXUh+/aIsSbb5c7qB3
ZetUN/cZjkLZOLdRQ6iRk7NNVvTXAHC+cCjag5N8iF+Z6hIMNflaeV+85B4TMB8UyYfQAA
AMEAkXYftB5l07tIqABANlD9htruSRK2/ToeTEkLtm+PCH5gbze1w+vTssyTXmB6Qdo/kM
1gLSbkWGYJw9TOW88nC1L7TMp8VdDwPssTWyDrirz01OYFVuXruFcQUIT2tTRsOR5M4Rx1
XzyXG3F5mRccJLQd1pGbz5pB1uMt3TmH6gUMgxnCun1LZN6/EorDILAOHAA7j3xguWkZmZ
OmNMJzqUrfZ0y7VIz/lbh832yrTW9uK0dnlngUqv7KchO77KPPAAAAwQD9w0l4gERT931G
K6brBtQYIsQ8qCVjK6K7kOrniorzu616HGrpCrqgcb9cWAh0B9B/qPyNqGeQ6+GhAIxiE/
cklVe+HYxmGH9l4GHVJZqpjo10rzQznyYswQk3EdkJvBOtKTWInNADSFn5WANlNZAI8t0J
xd4IvYvH3ZJSSDIood7L0lvkjNjptx0CIRra+EGA7hW2Nac3OmDMPensJuo7tZRaRv1N+X
Au3Kd0NzYSc1NQo+mbeRNfalUqaBCBSSMAAADBAP25Ag2NSvyuTjsUcC43OPFXjeoPnq2b
+wDVmoBAdI4C1ACwxWt7z7AVy0eBuZxk/sr5sX+f9hkZcXxMjk55kHEAvtN1Unzqpidab0
jz1cxfb/ktk57DT4wuo5LsHKbKhnRbcTOdzvRawpTaW4DCs2pPAoVsLdQQ8Q3hzyzq2HZ+
4OXQRc8JK7thw+O3X7hzw6gCrozm7M908BEzg7T67OVx1ywt79ozedCq/gmNSNmJHRcvZb
Nrv8UoO+4M0hHUswAAAA5yb290QGZhbnl1MTk5NAECAw==
-----END OPENSSH PRIVATE KEY-----
'
          source: 'dist/'
          target: ${{ secrets.TAR }}