# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job password: ${{ secrets.SERVER_PASSWORD }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access   s
      - uses: actions/checkout@v2
      - name: use node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1
      - name: npm i && npm run build
        run: |
          npm i pnpm -g
          pnpm i
          pnpm build
      - name: scp file
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: 22
          username: 'root'
          # target: ${{secrets.SERVER_TARGET}}
          target: '/home/fy-three'
          source: './cicd/dockerBootstrap.sh'
      # 登录阿里云镜像容器服务，打包镜像，推送镜像
      - name: Build the Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}

          docker build -t fy-three:latest .

          docker tag fy-three:latest registry.cn-hangzhou.aliyuncs.com/fanyu1994/fy-three:latest

          docker push registry.cn-hangzhou.aliyuncs.com/fanyu1994/fy-three:latest
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: 'root'
          # key: ${{ secrets.SERVER_SSHKEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd /home/fy-three/cicd &&  sh dockerBootstrap.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
