# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job password: ${{ secrets.SERVER_PASSWORD }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access itd 
      - uses: actions/checkout@v2

      - name: scp file
        uses: appleboy/scp-action@master
        with:
          host:  ${{ secrets.HOST }}
          username: ${{ secrets.UN }}
          port: 22
          key: ${{ secrets.SSH }}
          source: ''
          target: ${{ secrets.TAR }}