# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job password: ${{ secrets.SERVER_PASSWORD }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access 
      - uses: actions/checkout@v2

      - name: scp file
        uses: appleboy/scp-action@master
        with:
          host:  ${{ secrets.HOST }}
          username: ${{ secrets.UN }}
          port: 22
          key: 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAytN/Z7wWQ/JhiM7gAw1ZzUelLQwGhyeE67m5P84V+NgbM+MmNXQ2
qwTx6n1XiUZ+FzATMiKjBZ8cLTa1Jk0xFUvEqsu1Th4n05eGbwb19+KS4mY1SP6KSweguW
7g+aFY4vR+0azcFyORhjn7fGG2BOQ5/y4Ev4maXaCX7sL7IQ0YiK4Y7370lXYbiBceqiAR
T5DVJkwJk793TWiqDvvpZRiCp1TzlOvN++tn+NOEiqc2SbbkYTEGlvogjJAijmZhisk581
ak7d4yj6Yp8AIclzHDwPpObv9mYJROXvASo0j9fi7275ukPz53cyyZe5QOrTQMjQC2XQ/e
FSbfFw7X8DhEjLeyw6QWKcV7fV74jnWGhuaPkH6Rm83QB7GagSJvNPexNmSEMeiv9pqeqo
rDCa23l2SfIZwmkOK3prqzipB1aBL+CbySjFHwSThBdwIHihB6+ZW4PZRD1p5lW2fC2BxW
oa8jIIYKPH6PpFd6fFrd6S7ko/ouULZmGeQLoqpPAAAFiMwwiCnMMIgpAAAAB3NzaC1yc2
EAAAGBAMrTf2e8FkPyYYjO4AMNWc1HpS0MBocnhOu5uT/OFfjYGzPjJjV0NqsE8ep9V4lG
fhcwEzIiowWfHC02tSZNMRVLxKrLtU4eJ9OXhm8G9ffikuJmNUj+iksHoLlu4PmhWOL0ft
Gs3BcjkYY5+3xhtgTkOf8uBL+Jml2gl+7C+yENGIiuGO9+9JV2G4gXHqogEU+Q1SZMCZO/
d01oqg776WUYgqdU85TrzfvrZ/jThIqnNkm25GExBpb6IIyQIo5mYYrJOfNWpO3eMo+mKf
ACHJcxw8D6Tm7/ZmCUTl7wEqNI/X4u9u+bpD8+d3MsmXuUDq00DI0Atl0P3hUm3xcO1/A4
RIy3ssOkFinFe31e+I51hobmj5B+kZvN0AexmoEibzT3sTZkhDHor/aanqqKwwmtt5dkny
GcJpDit6a6s4qQdWgS/gm8koxR8Ek4QXcCB4oQevmVuD2UQ9aeZVtnwtgcVqGvIyCGCjx+
j6RXenxa3eku5KP6LlC2ZhnkC6KqTwAAAAMBAAEAAAGAWvafnRZtpet+cqzVKolCTR5kpd
9Ozi6bHl0dB9CVahUBnjOxXyfPnMOK+29bYuWKhzu4YDPIiSzipiRy+cqEyNhCS5cwqOg9
VFgQopqslY+38HGGVEZUH3I8Uu23WD1Ub/TXK5Iq4vXAvkIi15W63Fa+7ALnfj9oS7VKbn
pjxl7pMeNiq4Z0itN9ZXt49TOMj/KUpahUYz7rcnwOSMoR0pU7g3BGDfPzXZgl+SJjvwte
/ZBYvH4QRoXHM0MxPEwNhmuytuzug5hjbwpw94lznllhu4DxTaQz3BUMo28yZoj8Vjaqcl
SbrNVWms6c/b4UzLTdbrRFot3nyXugRGoWudgRLTUA9t3CSyXccSPQqDZWHYt7XG3UBRCR
H1k8mYbtFEvNV76kkM62i3WPvdFBdIElAXkhBgHvfl+oylvwnzpVGIwhFuDTjnM4WfuXJj
keL9/sbc1Rz7jG+w73B1QahM0dhlywh1suUZtfOGRXPwfmY/HF8z8Uj+3G/mSJ3YaBAAAA
wQC2KA1q0CfyDSskMBt6Cxtfq84hguFgXrV7MXqRCK28IEWW06TgNxUssIQbvFa1wlPSay
IyMbqsH/0KGRLe5+vnOyT043MfMfKS7XWZN5ymFn2AA1YRlqlF0XJVKB4DaH/JrJMLBBxH
1cDvqbPLHiOXamA12u3kUsP4KjLjnQ73BdOpW/jSgCJiqahxRDYWPCpLoCVEqGriERL2Tl
P0Nzi0Gb1u9l7nS1V3Xs4v3uaEZRkqZDg7yZNzrzE0x1mzsxgAAADBAO31Jd3SNtr6WnV0
PJX9htHpmiA096FtZtHc2MBD7zoQbIBGgXxk0/0acY+HfmAJFtrbJKcVLUFIQvKe0TMGb2
rca5jyFjQ7vLrCP2ayJp6ssLnL2EF8koDtWIxgLG7m+qV3nypxRxV7lIVbrX9OYfB3NrdU
Ys0d1rwHSUpItbJw6u4lMsC8yojcJGMbRcrCaeKqszheCkfju2Xg5Rvu6LwrNYwwbvLztu
bNvANMzHXzoj4QSrtQRDOFQUBi5Ab5BQAAAMEA2jRvM3t2tZmBW27TjaD8jHM5MYpHfGqM
BwtG3HGyV5AO1rjunOPpv43D+Mgn9dHhAy16MUw2RJSlzRNTtWWuTgtXlRggkV6nZXcdOs
Q3bHLdtfUDDN9K4+4R5AZZ+soZmgOcHoUJ+LjajW4WNWZ4vTbWsl7PxyiyxdBcBJvXs8t4
eVxcMN+jXmbTctSB28RioJXkEG1V6VV5Wzo1N/05xTHpCCrAIKYQnEK6GAWqgv8V8E8mnc
jsWjXSYh0p0eZDAAAAETEwMjUxNTM2OTdAcXEuY29tAQ=='
          source: 'dist/'
          target: ${{ secrets.TAR }}